spring.profiles.active=dev

spring.application.name=schoolapp
#server.servlet.context-path=/schoolapp

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Το session κλείνει αυτόματα όταν επιστρέψει το service
# αν ήταν true, θα κρατούσε το session ανοιχτό και θα μπορούσε να κάνει lazy loading
# n + 1 queries -> very slow process/massive data load when OSIV = true
# Best practice είναι false
# JOIN FETCH ή EntityGraph
# DO NOT FORGET - > JOIN FETCH ή @EntityGraph
spring.jpa.open-in-view=false

server.forward-headers-strategy=framework
# Aforementioned command is used for: real client's IP,
# not of the load balancer (proxy)